name: satuarah
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  cloud_firestore: ^4.5.3
  cupertino_icons: ^1.0.2
  dropdown_search: ^5.0.6
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  firebase_storage: ^11.0.16
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_switch: ^0.3.2
  get: 4.6.5
  google_fonts: ^4.0.4
  image_picker: ^0.8.7
  intl: ^0.17.0

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
