name: satuarah
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  cloud_firestore: ^4.5.3
  cupertino_icons: ^1.0.2
  dio: ^5.2.1+1
  dropdown_search: ^5.0.6
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  firebase_storage: ^11.0.16
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_polyline_points: ^1.0.0
  flutter_rating_bar: ^4.0.1
  flutter_switch: ^0.3.2
  geocoding: ^2.0.0
  get: 4.6.5
  google_fonts: ^4.0.4
  google_maps_flutter: ^2.3.1
  image_picker: ^0.8.7
  intl: ^0.17.0

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 20

flutter:
  uses-material-design: true
  assets:
    - assets/
